#!/bin/bash
  # set -x

  if [ -n "$1" ] ;then
    SRC=$1
  else
    echo exit with no src
    exit
  fi

  if [ -n "$2" ] ;then
    DST=$2
  else
    echo exit with no dst
    exit
  fi

  sed -i 's/'$SRC'/'$DST'/g' `grep $SRC . -rl`
